### ISSUE TITLE
Can I Help?

### ISSUE THREAD

**Issue by radioblahaj** [amazinigmech2418/Waffle-programming#2]
I an FLuent in front dev ( html,css and js) Designing Models and Html,css and js for this.
You might heard i copy work, I will promise not to from or for this project. Please Allow Me  to help, it will be a great pleasure to help. :)

**Comment by AmazingMech2418** [comment]
I'll invite you very soon. Congratulations! You're now a waffle developer! Please join the studio too.

**Comment by radioblahaj** [comment]
sure! Thanks!

**Comment by radioblahaj** [comment]
studio?

**Comment by AmazingMech2418** [comment]
You're welcome! The studio is curated by @stymphalianbirb on scratch and @pokemonscratch101 on scratch as well as me.

**Comment by radioblahaj** [comment]
no invite.

**Comment by AmazingMech2418** [comment]
?

**Comment by radioblahaj** [comment]
in studio

**Comment by AmazingMech2418** [comment]
OK. I'll invite you.
