### ISSUE TITLE
Let's Talk here!

### ISSUE THREAD

**Issue by radioblahaj** [amazinigmech2418/Waffle-programming#4]
I Can Make a org for this.

**Comment by radioblahaj** [comment]
I am Making it now!

**Comment by radioblahaj** [comment]
Complte, Invited Members of team, invte rest
https://github.com/Waffleprograming/Waffle-Programinng

**Comment by AmazingMech2418** [comment]
Nice! That's a great idea!

**Comment by radioblahaj** [comment]
Should Delate this. or acrhive.

**Comment by radioblahaj** [comment]
so, is waffle a drag and drop website?

**Comment by AmazingMech2418** [comment]
Yes.

**Comment by radioblahaj** [comment]
drag and drop, cool, are we adding 3d?

**Comment by AmazingMech2418** [comment]
Yes. I already have a 3d engine in mechJS.

**Comment by radioblahaj** [comment]
so like scratch, but 3D cool!

**Comment by AmazingMech2418** [comment]
Yes. That's what waffle is.
